name: Build Function App Package

on:
  push:
    branches: [ main ]
    paths:
      - 'function-app/**'
      - '.github/workflows/build-function-app.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'function-app/**'
  workflow_dispatch:  # Allow manual trigger

env:
  PYTHON_VERSION: '3.11'

jobs:
  build:
    name: Build Function App Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: function-app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if available)
        working-directory: function-app
        run: |
          if [ -f "requirements-dev.txt" ]; then
            pip install -r requirements-dev.txt
          fi
          
          if [ -d "tests" ]; then
            pip install pytest pytest-cov
            pytest tests/ --cov=. --cov-report=term
          else
            echo "No tests directory found, skipping tests"
          fi

      - name: Create deployment package
        working-directory: function-app
        run: |
          # Create the deployment zip exactly as specified
          zip -r ../function-app-deploy.zip . \
            -x "*.git*" \
            -x "*.venv*" \
            -x "*.vscode*" \
            -x "*__pycache__*" \
            -x "*.pytest_cache*" \
            -x "tests/*" \
            -x "*.pyc" \
            -x "*.pyo" \
            -x "*.pyd" \
            -x ".coverage" \
            -x "*.egg-info/*" \
            -x "requirements-dev.txt"
          
          # Show package info
          echo "📦 Package created successfully!"
          echo "Size: $(du -h ../function-app-deploy.zip | cut -f1)"
          echo "Contents preview:"
          unzip -l ../function-app-deploy.zip | head -20

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-app-deploy-${{ github.sha }}
          path: function-app-deploy.zip
          retention-days: 30

      - name: Create Release (on main branch only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: function-app-${{ github.run_number }}
          name: Function App Build ${{ github.run_number }}
          body: |
            Automated build of Function App
            
            **Commit:** ${{ github.sha }}
            **Build Number:** ${{ github.run_number }}
            **Triggered by:** ${{ github.actor }}
            
            ### Changes
            ${{ github.event.head_commit.message }}
            
            ### Download
            The `function-app-deploy.zip` file below is ready for deployment to Azure Functions.
          files: function-app-deploy.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Function App package built successfully!\n\n📦 [Download artifact](${artifactUrl})\n\nPackage name: \`function-app-deploy-${{ github.sha }}.zip\``
            })